### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by jumentib** [lutsik/MeDeCom#14]
Hello,
I am trying to install the MeDeCom package but I have this error message:

Error: package or namespace load failed for ‘MeDeCom’ in dyn.load(file, DLLpath = DLLpath, ...):
 impossible de charger l'objet partagé '/Users/jumentib/Library/R/3.5/library/MeDeC/libs/MeDeCom.so':
  dlopen(/Users/jumentib/Library/R/3.5/library/MeDeCom/libs/MeDeCom.so, 6): Symbol not found: __ZNSt15basic_streambufIcSt11char_traitsIcEE5imbueERKSt6locale

Do you know what this symbol means: "__ZNSt15basic_streambufIcSt11char_traitsIcEE5imbueERKSt6locale".

Note, at first I had an error message about a file "omp.h".

Do you have an idea to solve this problem? 
I'm working on Mac with version 3.5.1 of R.

Thanks, Basile

ps: I'll be at the Aussois data challenge in December.

**Comment by lutsik** [comment]
Hi Basile,

Great to see the workshop participants here.

As stated in the vignette, we are currently supporting Linux machines exclusively, due to the issues with the shared libraries, in particular OpenMPI. However, the plan is to add (at least) the OS X support by early December. We will keep you posted.

Best,

Pavlo

**Comment by privefl** [comment]
Hi Pavlo, 

We expect that a large proportion of people will have non-Linux machines at the workshop.

I understand that you use fancy stuff like OpenMPI to speed up things.
Yet, would it be possible to make a lightweight version of MeDeCom that can be used on all platforms (even if it's 5x slower)?

Best,
Florian

**Comment by lutsik** [comment]
Hi Florian,

Thanks for pointing this out. We will work on this in the remaining time. 

Speaking generally, I have to note though that a full-blown MeDeCom analysis using standard laptops is difficult at the moment. We will think how to overcome this.

Best regards,

Pavlo
