### ISSUE TITLE
proportion.feature.corr  throws an error

### ISSUE THREAD

**Issue by shashwatsahay** [lutsik/MeDeCom#19]
Error in xy.coords: 'x' and 'y' lengths differ 
or
Error in data.frame: arguments imply differing number of rows: 0, 473

line 197 (could be due to NA value?)

**Comment by schmic05** [comment]
Fixed by commits 0b53eeea4d5fd61b7821a94e912374819a8deb77 and 89bdb0c0ea151073d1a888185dbb79fea28e309d
