### ISSUE TITLE
Install MeDeCom/man/locus_plot.Rd:38: unknown macro '\cs' Error

### ISSUE THREAD

**Issue by liuyang2006** [lutsik/MeDeCom#24]
Dear author:

When I install MeDeCom, the man folder occur an error about latex macro. Can you help me to find the fixed methods?

Following error:

/private/var/folders/95/4csz2hdx2hg_fn3n561hx7td4mjl7w/T/RtmpUITQuB/Rbuild21f35378bbed/MeDeCom/man/locus_plot.Rd:38: unknown macro '\cs'

Best,
Yang

**Comment by lutsik** [comment]
Hi, This was recently fixed in the devel branch, but did not make it into master yet. A workaround for now would be to install the former.

**Comment by liuyang2006** [comment]
Can you send me the corrected version first, I would like to use this tool to done some analysis. Thank you!

ieyangliu@zzu.edu.cn
Yang Liu

**Comment by schmic05** [comment]
@liuyangzzu You should now be able to install MeDeCom directly from GitHub as:
`devtools::install_github("lutsik/MeDeCom")`
