### ISSUE TITLE
Running time too long problem

### ISSUE THREAD

**Issue by liuyang2006** [lutsik/MeDeCom#27]
Dear author,
I have installed and use your program correctly. However, the running time is very high, just for library's demo data set D [10000, 100],  need running more than five hours. I am wandering if I use the correct way to call MeDeCom methods?

Another question is that, is it feasible for me to run current MeDeCom on 450K array data? Can it generate results at a specific time range? If you have any suggestions, that will be great! Thank you again!

Below is my code for demo datasets, it takes more than five hours generate results:

====================================================

library(MeDeCom)
data(example.dataset, package="MeDeCom")
medecom.result<-runMeDeCom(D, Ks=4:15, lambdas=c(0,10^(-5:-1)), NFOLDS=5, verbosity=1L, NCORES=8)

====================================================

Best, 
Yang Liu
Zhengzhou University
ieyangliu@zzu.edu.cn

**Comment by schmic05** [comment]
Dear Yang Liu,

Indeed, in the default setting, MeDeCom runs for some time. Please note that MeDeCom executes a run for each combination of your K and lambda value, and furthermore employs a cross-validation scheme. This is why a single execute might take up to 24 hours depending on your computer setup.

We recently presented a new start-to-finish protocol to perform reference-free deconvolution of complex DNA methylation data, obtained from the Illumina BeadArrays (https://www.biorxiv.org/content/10.1101/853150v1). You should have a look at this and analyze your data accordingly.

Hope that helps,

Michael
