### ISSUE TITLE
Qsub problem

### ISSUE THREAD

**Issue by liuyang2006** [lutsik/MeDeCom#28]
Hi Michael,
Thank you for your timely respond.
I can get results on HPC now. However when I use qsub methods you provided on GitHub. I get error, I think it is a small bug or my mistakes? Do you know how to solve this error?

Qsub code from GitHub is

medecom.result<-runMeDeCom(D, Ks=2:10, lambdas=c(0,10^(-5:-1)), N_COMP_LAMBDA=1, NFOLDS=5, NINIT=10, 
temp.dir="/cluster_fs/medecom_temp",
cluster.settings=sge.setup)

**Below is the error report for qsub error:**

qsub:  file must be an ascii script
qsub:  file must be an ascii script
qsub:  file must be an ascii script
qsub:  file must be an ascii script
qsub:  file must be an ascii script
qsub:  file must be an ascii script
qsub: script file 'cv_demo_1_1_4*,cv_demo_1_1_4_6' cannot be loaded - No such file or directory
qsub: script file 'cv_demo_1_1_4*,cvfine_demo_1_1_4_tb_5_6' cannot be loaded - No such file or directory
qsub: script file 'cv_demo_1_1_4*,cvfine_demo_1_1_4_tb_4_5' cannot be loaded - No such file or directory

.........

**Comment by schmic05** [comment]
Hi @liuyangzzu,

Can you show me how you configures your SGE setting, i.e. how the variable `sge.setup` looks like?
