### ISSUE TITLE
MeDeCom crashes when NFOLDS=1

### ISSUE THREAD

**Issue by nikitaved** [lutsik/MeDeCom#4]
I think we just have to make a warning like 'NFOLDS>1'
Also NFOLDS cannot be greater than the number of columns

**Comment by nikitaved** [comment]
@schmic05, this issue is resolved as far as I can see from the history, right? If so, please close the issue then.

**Comment by schmic05** [comment]
Fixed with https://github.com/lutsik/MeDeCom/commit/26e3cb97a2dbb2f9da60fa622e8af1dc108487c8

**Comment by nikitaved** [comment]
@schmic05, is it true that NFOLDS cannot exceed the number of columns?

**Comment by schmic05** [comment]
@nikitaved That's a good question. I will have to check this.

**Comment by schmic05** [comment]
It also works when the number of NFOLDS is larger than the number of columns.

**Comment by nikitaved** [comment]
Does it make sense to have NFOLDS larger than the number of columns?

**Comment by schmic05** [comment]
No, not really. Cross-validation shouldn't have a repeated sample, then it would be mixed with bootstrapping and these are typically two distinct methods. Anyhow, I think the program is fine in the current state.
